version: '3.10'

services:
  api:
    container_name: api
    env_file: ./backend/.env
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend/app:/app
    depends_on:
      - db
    ports:
      - 3000:3000


  frontend:
    container_name: frontend
    env_file: ./frontend/.env
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 8080:8080
    restart: always
    tty: true
    depends_on:
      - api
      - db
    volumes:
      - ./frontend/app:/app
    environment:
      - VUE_APP_API_URL="localhost"


  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: a3_db
      MYSQL_USER: a3
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - ./db/data:/var/lib/mysql
      #- ./db/conf.d/my.conf:/etc/mysql/conf.d/my.cnf
      #- ./db/sql:/tmp
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    tty: true

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_HOSTS=db
    ports:
    - 127.0.0.1:8888:80

  nginx:
    build: ./server
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./frontend/app:/var/www/html
      - ./server/conf.d/nginx.conf:/etc/nginx/nginx.conf
      #- ./server/conf.d:/etc/nginx/conf.d

