"""Added columns.

Revision ID: 03af7f9b67b2
Revises: 8ff66d484a9a
Create Date: 2022-12-07 00:10:41.387620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03af7f9b67b2'
down_revision = '8ff66d484a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('sex', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'sex')
    # ### end Alembic commands ###
